-- Q_PRESTAMO -> Q_LOAN
/*
PARAMETROS:
:P_LOAN_NBR
:p_rate_type
 */
select
    a.BRANCH_CODE AS BRANCH_CODE,
    a.SUBAPPLICATION_CODE AS SUBAPPLICATION_CODE,
    LOAN_NBR AS LOAN_NBR,
    COMPLETE_NAME AS full_name,
    decode (
        TASA_TYPE,
        '0',
        'Fixed',
        '1',
        'Floating',
        '5',
        'Periodic F',
        'Other'
    ) AS rate_type,
    PORTFOLIO_RATE_VALUE_CODE AS PORTFOLIO_RATE_VALUE_CODE,
    BASE_CURRENT_INT_RATE AS BASE_CURRENT_INT_RATE,
    MATHEMATICAL_RELATION_1 AS MATHEMATICAL_RELATION_1,
    CURRENT_SPREAD_1 AS CURRENT_SPREAD_1,
    TOTAL_QUANTITY AS TOTAL_QUANTITY,
    decode (
        REVISION_FREQUENCY_TYPE,
        2,
        'Monthly',
        1,
        'Daily',
        null
    ) AS rate_revision_frequency,
    PERIOD_RATE AS PERIOD_RATE,
    RATE_REVISION_DAY AS RATE_REVISION_DAY,
    DATE_INTEREST_RATE_LAST_REVISION AS DATE_INTEREST_RATE_LAST_REVISION,
    REVISION_DATE_INT AS REVISION_DATE_INT,
    NEXT_PRINCIPAL_PAYMENT_DATE AS NEXT_PRINCIPAL_PAYMENT_DATE,
    NEXT_INTEREST_PAYMENT_DATE AS NEXT_INTEREST_PAYMENT_DATE,
    c.DESCRIPTION AS DESCRIPTION,
    M.BRANCH_NAME AS BRANCH_NAME,
    a.DUE_DATE AS DUE_DATE,
    a.OPENING_DATE AS OPENING_DATE
from
    PR_LOANS a,
    MG_CLIENTS b,
    MG_SUBAPPLICATIONS c,
    MG_BRANCHES M
where
    b.CLIENT_CODE = a.CLIENT_CODE
    AND A.COMPANY_CODE = M.COMPANY_CODE
    AND A.BRANCH_CODE = M.BRANCH_CODE
    and a.SUBAPPLICATION_CODE = c.SUBAPPLICATION_CODE
    and c.APPLICATION_CODE = 'BPR'
    and LOAN_NBR = nvl (P_LOAN_NBR, LOAN_NBR)
    AND nvl (TASA_TYPE, '9') = nvl (P_RATE_TYPE, nvl (TASA_TYPE, '9'))
    AND a.STATE = 1
ORDER BY
    a.BRANCH_CODE,
    SUBAPPLICATION_CODE,
    TASA_TYPE