-- Q_1:
SELECT  A.LEVEL_1,A.LEVEL_2,A.LEVEL_3,A.LEVEL_4,
               A.LEVEL_5,A.LEVEL_6,A.LEVEL_7,A.LEVEL_8,              
              DECODE(P_MONTH,1,A.MONTH_1_BALANCE,
              2,A.MONTH_2_BALANCE,3,A.MONTH_3_BALANCE,
              4,A.MONTH_4_BALANCE,5,A.MONTH_5_BALANCE,
              6,A.MONTH_6_BALANCE,7,A.MONTH_7_BALANCE,
              8,A.MONTH_8_BALANCE,9,A.MONTH_9_BALANCE,
              10,A.MONTH_10_BALANCE,11,A.MONTH_11_BALANCE,
              12,A.MONTH_12_BALANCE) BALANCE, B.DESCRIPTION, C.TYPE_CODE
FROM    GM_BALANCES_MONTHLY A,
              GM_ACCOUNT_BALANCE    B,
              GM_CATALOGS C
WHERE a.LEVEL_1 BETWEEN nvl(P_LEVEL_1,a.LEVEL_1) AND          DECODE(P_LEVEL_1_1,NULL,DECODE(P_LEVEL_1,NULL,a.LEVEL_1,P_LEVEL_1),P_LEVEL_1_1) 
AND a.LEVEL_2 BETWEEN nvl(P_LEVEL_2,a.LEVEL_2) AND    DECODE(P_LEVEL_2_2,NULL,DECODE(P_LEVEL_2,NULL,a.LEVEL_2,P_LEVEL_2),P_LEVEL_2_2) 
AND a.LEVEL_3 BETWEEN nvl(P_LEVEL_3,a.LEVEL_3) AND   DECODE(P_LEVEL_3_3,NULL,DECODE(P_LEVEL_3,NULL,a.LEVEL_3,P_LEVEL_3),P_LEVEL_3_3) 
 AND a.LEVEL_4 BETWEEN nvl(P_LEVEL_4,a.LEVEL_4) AND   DECODE(P_LEVEL_4_4,NULL,DECODE(P_LEVEL_4,NULL,a.LEVEL_4,P_LEVEL_4),P_LEVEL_4_4) 
AND  a.LEVEL_5 BETWEEN nvl(P_LEVEL_5,a.LEVEL_5) AND   DECODE(P_LEVEL_5_5,NULL,DECODE(P_LEVEL_5,NULL,a.LEVEL_5,P_LEVEL_5),P_LEVEL_5_5)
 AND a.LEVEL_6  BETWEEN nvl(P_LEVEL_6,a.LEVEL_6) AND   DECODE(P_LEVEL_6_6,NULL,DECODE(P_LEVEL_6,NULL,a.LEVEL_6,P_LEVEL_6),P_LEVEL_6_6) 
 AND a.LEVEL_7 BETWEEN nvl(P_LEVEL_7,a.LEVEL_7) AND   DECODE(P_LEVEL_7_7,NULL,DECODE(P_LEVEL_7,NULL,a.LEVEL_7,P_LEVEL_7),P_LEVEL_7_7)
 AND a.LEVEL_8 BETWEEN nvl(P_LEVEL_8,a.LEVEL_8) AND   DECODE(P_LEVEL_8_8,NULL,DECODE(P_LEVEL_8,NULL,a.LEVEL_8,P_LEVEL_8),P_LEVEL_8_8) 
AND B.LEVEL_1=A.LEVEL_1
AND B.LEVEL_2=A.LEVEL_2
AND B.LEVEL_3=A.LEVEL_3
AND B.LEVEL_4=A.LEVEL_4
AND B.LEVEL_5=A.LEVEL_5
AND B.LEVEL_6=A.LEVEL_6
AND B.LEVEL_7=A.LEVEL_7
AND B.LEVEL_8=A.LEVEL_8
AND  A.YEAR=P_YEAR 
AND A.COMPANY_CODE = B.COMPANY_CODE
AND B.COMPANY_CODE = C.COMPANY_CODE
and   b.RECEIVES_MOVEMENT = 'S'
AND a.LEVEL_1 = c.LEVEL_1 
AND a.LEVEL_2 = c.LEVEL_2 
AND a.LEVEL_3 = c.LEVEL_3 
AND a.LEVEL_4 = c.LEVEL_4
AND a.LEVEL_5 = c.LEVEL_5 
AND a.LEVEL_6 = c.LEVEL_6
AND c.COMPANY_CODE  = P_COMPANY_CODE 
ORDER BY 1,2,3,4,5,6,7,8

-- funciones:

--F_CF_FORMULA
function CF_1 return VARCHAR2 is
PV_FORMATO VARCHAR2(39);
begin
GM_F_DESPLEGAR_R(Q_1.LEVEL_1,Q_1.LEVEL_2,Q_1.LEVEL_3,Q_1.LEVEL_4,Q_1.LEVEL_5,Q_1.LEVEL_6,
                Q_1.LEVEL_7,Q_1.LEVEL_8,Q_1.P_COMPANY_CODE,PV_FORMATO);
 RETURN (PV_FORMATO); 
end;