/* ORDEN DE CAMPOS:
(10)CF - F_CUENTA.Q_CUENTA.CF_ACCOUNT
(20)BD - DESCRIPCION.Q_CUENTA.DESCRIPTION
(30)BD - F_PERMITIR_SOBREGIRO.Q_CUENTA.ACCOUNT_CLASS
(40)BD - F_RECIBE_MOV.Q_CUENTA.TXN_ENTRY_RECEIVED
(50)BD - F_1.Q_CUENTA.AUXILIARY_CODE
(60)BD - F_2.Q_CUENTA.AUXILIARY_DESCRIPTION
 */
-- Q_CUENTA -> Q_ACCOUNT
/*
PARAMETROS:
P_TYPE_CODE
P_LEVEL_1
 */
SELECT
  a.LEVEL_1 AS LEVEL_1,
  a.LEVEL_2 AS LEVEL_2,
  a.LEVEL_3 AS LEVEL_3,
  a.LEVEL_4 AS LEVEL_4,
  a.LEVEL_5 AS LEVEL_5,
  a.LEVEL_6 AS LEVEL_6,
  a.LEVEL_7 AS LEVEL_7,
  a.LEVEL_8 AS LEVEL_8,
  a.DESCRIPTION AS ACCOUNT_DESCRIPTION,
  a.ALLOW_OVERDRAFT AS ALLOW_OVERDRAFT,
  a.REQUEST_OVERDRAFT_AUTHORIZATION AS REQUEST_OVERDRAFT_AUTHORIZATION,
  a.ENABLE_TXN_ENTRY AS ENABLE_TXN_ENTRY,
  NVL (a.MAX_LIMIT, 0) AS MAX_LIMIT,
  NVL (a.MIN_LIMIT, 0) AS MIN_LIMIT,
  d.DESCRIPTION AS AUXILIARY_DESCRIPTION,
  a.TXN_ENTRY_RECEIVED AS TXN_ENTRY_RECEIVED,
  b.ACCOUNT_CLASS AS ACCOUNT_CLASS,
  b.TYPE_CODE AS TYPE_CODE,
  c.AUXILIARY_CODE AS AUXILIARY_CODE
FROM
  GM_ACCOUNT_BALANCE a,
  GM_CATALOGS b,
  GM_AUXILIARY_BALANCE c,
  GM_CODES_AUXILIARY d
WHERE
  a.LEVEL_1 = b.LEVEL_1
  AND a.LEVEL_2 = b.LEVEL_2
  AND a.LEVEL_3 = b.LEVEL_3
  AND a.LEVEL_4 = b.LEVEL_4
  AND a.LEVEL_5 = b.LEVEL_5
  AND a.LEVEL_6 = b.LEVEL_6
  AND a.LEVEL_1 = c.LEVEL_1 (+)
  AND a.LEVEL_2 = c.LEVEL_2 (+)
  AND a.LEVEL_3 = c.LEVEL_3 (+)
  AND a.LEVEL_4 = c.LEVEL_4 (+)
  AND a.LEVEL_5 = c.LEVEL_5 (+)
  AND a.LEVEL_6 = c.LEVEL_6 (+)
  AND a.LEVEL_7 = c.LEVEL_7 (+)
  AND a.LEVEL_8 = c.LEVEL_8 (+)
  AND a.COMPANY_CODE = c.COMPANY_CODE (+)
  AND c.AUXILIARY_CODE = d.AUXILIARY_CODE (+)
  AND b.TYPE_CODE = NVL (p_TYPE_CODE, b.TYPE_CODE)
  AND a.LEVEL_1 = NVL (p_LEVEL_1, a.LEVEL_1)
ORDER BY
  a.LEVEL_1,
  a.LEVEL_2,
  a.LEVEL_3,
  a.LEVEL_4,
  a.LEVEL_5,
  a.LEVEL_6,
  a.LEVEL_7,
  a.LEVEL_8,
  c.AUXILIARY_CODE
  -- Functions:
  --PARAMETRO: P_COMPANY_CODE
  function CF_ACCOUNT return VARCHAR2 is BEGIN DECLARE Lv_FORMAT VARCHAR(39);

begin GM_P_DESPLEGAR_R (
  Q_ACCOUNT.LEVEL_1,
  Q_ACCOUNT.LEVEL_2,
  Q_ACCOUNT.LEVEL_3,
  Q_ACCOUNT.LEVEL_4,
  Q_ACCOUNT.LEVEL_5,
  Q_ACCOUNT.LEVEL_6,
  Q_ACCOUNT.LEVEL_7,
  Q_ACCOUNT.LEVEL_8,
  P_COMPANY_CODE,
  Lv_FORMAT
);

RETURN (Lv_FORMAT);

end;

RETURN NULL;

END;