/*
    (10) BD - FECHA_ENTREGA.Q_REPORTES.DELIVERY_DATE
    (20) BD - F_MES_FISCAL.Q_REPORTES.MONTH_FISCAL
    (30) BD - F_ANIO_FISCAL.Q_REPORTES.FISCAL_YEAR
    (40) BD - DESCRIPCION.Q_REPORTES.DESCRIPTION
    (50) CF - F_ANULADO_VIGENTE1.Q_REPORTES.CF_STATUS
*/

-- Q_REPORTES
SELECT
    FISCAL_YEAR,
    CURRENT_CANCELLED,
    COMPANY_CODE,
    DESCRIPTION,
    DELIVERY_DATE,
    MONTH_FISCAL
FROM
    GM_OFFICIAL_REPORTS_DELIVERY
WHERE
    COMPANY_CODE = P_COMPANY_CODE
    -- No hay datos

-- Functions:
function CF_STATUS return VARCHAR2 is
begin
  if :CURRENT_CANCELLED = 'C' THEN
     RETURN('CANCELED');
  ELSIF :CURRENT_CANCELLED = 'A' THEN
     RETURN('ACTIVE');
  END IF;
RETURN NULL; end;