-- Q_CUENTA
SELECT
    NIVEL_1,
    NIVEL_2,
    NIVEL_3,
    NIVEL_4,
    NIVEL_5,
    NIVEL_6,
    NIVEL_7,
    NIVEL_8,
    GM_BALANCE_EXTRANJEROS.DESCRIPCION,
    GM_BALANCE_EXTRANJEROS.CODIGO_MONEDA,
    MG_MONEDAS.DESCRIPCION,
    PERMITIR_SOBREGIRO,
    PEDIR_AUTORIZACION_SOBREGIRO,
    PERMITIR_MOVIMIENTO,
    NVL (LIMITE_MAXIMO, 0),
    NVL (LIMITE_MINIMO, 0)
FROM
    GM_BALANCE_EXTRANJEROS,
    MG_MONEDAS
WHERE
    GM_BALANCE_EXTRANJEROS.CODIGO_MONEDA = MG_MONEDAS.CODIGO_MONEDA
ORDER BY
    NIVEL_1,
    NIVEL_2,
    NIVEL_3,
    NIVEL_4,
    NIVEL_5,
    NIVEL_6,
    NIVEL_7,
    NIVEL_8

    -- FUNCIONES:
    -- F_CUENTA:
function CF_CUENTAFormula return VARCHAR2 is
    BEGIN
        DECLARE
        Lv_FORMATO VARCHAR(39);
        begin
        GM_P_DESPLEGAR_R(:NIVEL_1,:NIVEL_2,:NIVEL_3,:NIVEL_4,:NIVEL_5,:NIVEL_6,:NIVEL_7,:NIVEL_8,:P_CODIGO_EMPRESA,Lv_FORMATO);
        RETURN(Lv_FORMATO);  
        end;
        RETURN NULL; 
    END;