-- Q_CUENTA --> Q_ACCOUNT
SELECT
    LEVEL_1 LEVEL_1,
    LEVEL_2 LEVEL_2,
    LEVEL_3 LEVEL_3,
    LEVEL_4 LEVEL_4,
    LEVEL_5 LEVEL_5,
    LEVEL_6 LEVEL_6,
    LEVEL_7 LEVEL_7,
    LEVEL_8 LEVEL_8,
    GM_FOREIGN_BALANCE.DESCRIPTION BALANCE_DESCRIPTION,
    GM_FOREIGN_BALANCE.CURRENCY_CODE CURRENCY_CODE,
    MG_CURRENCY.DESCRIPTION CURRENCY_DESCRIPTION,
    ALLOW_OVERDRAFT ALLOW_OVERDRAFT,
    REQUEST_OVERDRAFT_AUTHORIZATION REQUEST_OVERDRAFT_AUTHORIZATION,
    ENABLE_TXN_ENTRY ENABLE_TXN_ENTRY,
    NVL (MAX_LIMIT, 0),
    NVL (MIN_LIMIT, 0)
FROM
    GM_FOREIGN_BALANCE,
    MG_CURRENCY
WHERE
    GM_FOREIGN_BALANCE.CURRENCY_CODE = MG_CURRENCY.CURRENCY_CODE
ORDER BY
    LEVEL_1,
    LEVEL_2,
    LEVEL_3,
    LEVEL_4,
    LEVEL_5,
    LEVEL_6,
    LEVEL_7,
    LEVEL_8
    -- FUNCIONES:
    -- F_CUENTA:
    function CF_ACCOUNT return VARCHAR2 is BEGIN DECLARE Lv_FORMAT VARCHAR(39);

begin GM_P_DESPLEGAR_R (
    Q_ACCOUNT.LEVEL_1,
    Q_ACCOUNT.LEVEL_2,
    Q_ACCOUNT.LEVEL_3,
    Q_ACCOUNT.LEVEL_4,
    Q_ACCOUNT.LEVEL_5,
    Q_ACCOUNT.LEVEL_6,
    Q_ACCOUNT.LEVEL_7,
    Q_ACCOUNT.LEVEL_8,
    P_COMPANY_CODE,
    Lv_FORMAT
);

RETURN (Lv_FORMAT);

end;

RETURN NULL;

END;