/*
ORDEN DE LOS CAMPOS:
(10) BD - F_codigo_criterio.Q_ONE
(20) BD - F_decriterio.Q_ONE
(30) BD - F_codigo_entidad.Q_ONE
(40) BD - F_descentidad.Q_ONE
(50) BD - F_valor.Q_ONE
(60) SUMATORIA - CS_TotalCriterio
 */
-- Q_1 --> Q_ONE
/*
PARAMETROS:
P_COMPANY_CODE
P_CRITERION_CODE
 */
SELECT
    a.CRITERION_CODE AS CRITERION_CODE,
    b.DESCRIPTION AS DESCRIPTION_CRITERION,
    a.ENTITY_CODE AS ENTITY_CODE,
    c.DESCRIPTION AS DESCRIPTION_ENTITY,
    a.VALUE AS VALUE
FROM
    GM_CRITICAL_VALUES_BY_ENTITY a,
    GM_DISTRIBUTION_CRITERION b,
    GM_COST_CENTERS c
WHERE
    a.COMPANY_CODE = NVL (P_COMPANY_CODE, a.COMPANY_CODE)
    and a.CRITERION_CODE = nvl (P_CRITERION_CODE, a.CRITERION_CODE)
    and b.COMPANY_CODE = a.COMPANY_CODE
    and b.CRITERION_CODE = a.CRITERION_CODE
    and c.COMPANY_CODE = a.COMPANY_CODE
    and c.COST_CENTER = a.ENTITY_CODE
ORDER BY
    a.CRITERION_CODE,
    a.ENTITY_CODE
    -- No hay funciones