FUNCTION CF_COMPANY_NAME RETURN VARCHAR2 IS
  Lv_CompanyName VARCHAR2(30);
BEGIN
  SELECT NAME
    INTO Lv_CompanyName
    FROM MG_EMPRESAS
   WHERE COMPANY_CODE = :P_COMPANY_CODE;
  
  RETURN(Lv_CompanyName);
  
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL;
END;




FUNCTION CF_TODAY_DATE RETURN DATE IS
  Ld_TodayDate DATE;
BEGIN
  SELECT TODAY_DATE
    INTO Ld_TodayDate
    FROM MG_SCHEDULE
   WHERE COMPANY_CODE = :P_COMPANY_CODE
     AND APPLICATION_CODE = :P_APPLICATION_CODE;
  
  RETURN Ld_TodayDate;
  
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL;
END;


FUNCTION CG$C_USER RETURN VARCHAR2 IS
BEGIN
  RETURN(:P_USER_REP);
END;