SELECT
    a.COMPANY_CODE,
    a.BRANCH_CODE,
    b.BRANCH_NAME,
    a.CURRENCY_CODE,
    a.CORRESPONDENT_BRANCH_CODE,
    a.ACCOUNT_NBR,
    a.INITIAL_CHECK_NBR,
    a.CHECK_QUANTITY,
    a.LAST_ISSUED_CHECK,
    d.NAME,
    e.DESCRIPTION,
    f.BRANCH_NAME
FROM
    BC_CHECKBOOKS a,
    MG_BRANCHES_GENERAL b,
    BC_CORRESPONDENT_ACCOUNTS c,
    MG_EMPRESAS d,
    MG_CURRENCY e,
    MG_BRANCHES_GENERAL f
WHERE
    a.CHECKRA_STATE = 1
    AND a.CHECKBOOK_TYPE = 'U'
    AND a.CORRESPONDENT_BRANCH_CODE = b.BRANCH_CODE
    AND c.COMPANY_CODE = a.COMPANY_CODE
    AND c.BRANCH_CODE = a.BRANCH_CODE
    AND c.CURRENCY_CODE = a.CURRENCY_CODE
    AND c.CORRESPONDENT_BRANCH_CODE = a.CORRESPONDENT_BRANCH_CODE
    AND c.ACCOUNT_NBR = a.ACCOUNT_NBR
    AND a.COMPANY_CODE = d.COMPANY_CODE
    AND a.CURRENCY_CODE = e.CURRENCY_CODE
    AND a.BRANCH_CODE = f.BRANCH_CODE
    AND c.CHECKBOOK_MANAGER = 'S'
    AND c.REORDER_POINT >= a.CHECK_QUANTITY - (
        SELECT
            SUM(x.CHECK_QUANTITY)
        FROM
            BC_CHECKBOOKS x
        WHERE
            x.CHECKRA_STATE = 1
            AND NVL (x.CHECKBOOK_TYPE, 'Z') <> 'U'
            AND x.COMPANY_CODE = a.COMPANY_CODE
            AND x.BRANCH_CODE = a.BRANCH_CODE
            AND x.CURRENCY_CODE = a.CURRENCY_CODE
            AND x.CORRESPONDENT_BRANCH_CODE = a.CORRESPONDENT_BRANCH_CODE
            AND x.ACCOUNT_NBR = a.ACCOUNT_NBR
        GROUP BY
            x.ACCOUNT_NBR
    )