-- Q_cr_dif_conciliacion (Credit Reconciliation Differences)
-- Parameters:
--   1. :p_numero_cuenta AS :p_account_nbr - Account number filter
--   2. :p_codigo_moneda AS :p_currency_code - Currency code filter (optional, can be NULL)
--   3. :p_codigo_corresponsal AS :p_correspondent_code - Correspondent branch code filter
--   4. :p_codigo_agencia AS :p_branch_code - Branch code filter
-- Fields:
--   1. secuencia_movimiento -> TXN_ENTRY_SEQ AS txn_seq_cr_dif
--   2. codigo_usuario_movimiento -> USERNAME AS user_cr_dif
--   3. fecha_movimiento -> TXN_ENTRY_DATE AS date_cr_dif
--   4. secuencia_movimiento_detalle -> TXN_ENTRY_DETAIL_SEQ AS detail_seq_cr_dif
--   5. numero_documento -> DOCUMENT_NBR AS doc_nbr_cr_dif
--   6. numero_referencia -> REFERENCE_NBR AS doc_nbr_cr_dif
--   7. diferencia -> DIFFERENCEVALUE AS amount_cr_dif
--   8. codigo_transaccion_concepto -> CONCEPT_TXN_CODE AS trn_cr_dif
--   9. codigo_aplicacion_auxiliar -> AUXILIARY_APPLICATION_CODE AS app_cr_dif
--   10. 'Transaction generated by reconciliation difference' AS detail_cr_dif
--   11. estado_conciliacion -> CONCILIATION_STATE
--   12. numero_cuenta -> ACCOUNT_NBR
--   13. codigo_moneda -> CURRENCY_CODE
--   14. codigo_agencia_corresponsal -> CORRESPONDENT_BRANCH_CODE
--   15. codigo_agencia -> BRANCH_CODE
--   16. conciliacion_global -> GLOBAL_RECONCILIATION
SELECT d.TXN_ENTRY_SEQ                    AS txn_seq_cr_dif,
       d.USERNAME                         AS user_cr_dif,
       d.TXN_ENTRY_DATE                   AS date_cr_dif,
       d.TXN_ENTRY_DETAIL_SEQ             AS detail_seq_cr_dif,
       d.DOCUMENT_NBR                     AS doc_nbr_cr_dif,
       a.DIFFERENCEVALUE                       AS amount_cr_dif,
       b.CONCEPT_TXN_CODE                 AS trn_cr_dif,
       b.AUXILIARY_APPLICATION_CODE       AS app_cr_dif,
       'Transaction generated by reconciliation difference' AS detail_cr_dif
  FROM BC_HISTORICAL_DAILY_RECONCILIATION a,
       BC_TXN_ENTRIES_HISTORICAL b,
       BC_DETAILS_HISTORICAL d,
       BC_PARAMETERS_GENERAL f
 WHERE a.TXN_ENTRY_SEQ = b.TXN_ENTRY_SEQ
   AND a.USERNAME = b.USER_CODE
   AND a.TXN_ENTRY_DATE = b.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_SEQ = d.TXN_ENTRY_SEQ
   AND a.USERNAME = d.USERNAME
   AND a.TXN_ENTRY_DATE = d.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_DETAIL_SEQ = d.TXN_ENTRY_DETAIL_SEQ
   AND a.CONCILIATION_STATE = 'C'
   AND a.DIFFERENCEVALUE IS NOT NULL
   AND a.ACCOUNT_NBR = :p_account_nbr
   AND a.CURRENCY_CODE = NVL(:p_currency_code, a.CURRENCY_CODE)
   AND a.CORRESPONDENT_BRANCH_CODE = :p_correspondent_code
   AND a.BRANCH_CODE = :p_branch_code
   AND a.DIFFERENCEVALUE > 0
   AND NVL(f.GLOBAL_RECONCILIATION, 'N') = 'N'
 UNION
SELECT d.TXN_ENTRY_SEQ                    AS txn_seq_cr_dif,
       d.USERNAME                         AS user_cr_dif,
       d.TXN_ENTRY_DATE                   AS date_cr_dif,
       d.TXN_ENTRY_DETAIL_SEQ             AS detail_seq_cr_dif,
       d.REFERENCE_NBR                    AS doc_nbr_cr_dif,
       a.DIFFERENCEVALUE                       AS amount_cr_dif,
       b.CONCEPT_TXN_CODE                 AS trn_cr_dif,
       b.AUXILIARY_APPLICATION_CODE       AS app_cr_dif,
       'Transaction generated by reconciliation difference' AS detail_cr_dif
  FROM BC_HISTORICAL_DAILY_RECONCILIATION a,
       BC_TXN_ENTRIES b,
       BC_TXN_ENTRY_DETAILS d,
       BC_PARAMETERS_GENERAL f
 WHERE a.TXN_ENTRY_SEQ = b.TXN_ENTRY_SEQ
   AND a.USERNAME = b.USER_CODE
   AND a.TXN_ENTRY_DATE = b.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_SEQ = d.TXN_ENTRY_SEQ
   AND a.USERNAME = d.USERNAME
   AND a.TXN_ENTRY_DATE = d.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_DETAIL_SEQ = d.TXN_ENTRY_DETAIL_SEQ
   AND a.CONCILIATION_STATE = 'C'
   AND a.DIFFERENCEVALUE IS NOT NULL
   AND a.ACCOUNT_NBR = :p_account_nbr
   AND a.CURRENCY_CODE = NVL(:p_currency_code, a.CURRENCY_CODE)
   AND a.CORRESPONDENT_BRANCH_CODE = :p_correspondent_code
   AND a.BRANCH_CODE = :p_branch_code
   AND a.DIFFERENCEVALUE > 0
   AND NVL(f.GLOBAL_RECONCILIATION, 'N') = 'N'
 UNION
SELECT d.TXN_ENTRY_SEQ                    AS txn_seq_cr_dif,
       d.USERNAME                         AS user_cr_dif,
       d.TXN_ENTRY_DATE                   AS date_cr_dif,
       d.TXN_ENTRY_DETAIL_SEQ             AS detail_seq_cr_dif,
       d.DOCUMENT_NBR                     AS doc_nbr_cr_dif,
       a.DIFFERENCEVALUE                       AS amount_cr_dif,
       b.CONCEPT_TXN_CODE                 AS trn_cr_dif,
       b.AUXILIARY_APPLICATION_CODE       AS app_cr_dif,
       'Transaction generated by reconciliation difference' AS detail_cr_dif
  FROM BC_HISTORICAL_DAILY_RECONCILIATION a,
       BC_TXN_ENTRIES_HISTORICAL b,
       BC_DETAILS_HISTORICAL d,
       BC_ACCOUNTS_RELATED e,
       BC_PARAMETERS_GENERAL f
 WHERE a.TXN_ENTRY_SEQ = b.TXN_ENTRY_SEQ
   AND a.USERNAME = b.USER_CODE
   AND a.TXN_ENTRY_DATE = b.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_SEQ = d.TXN_ENTRY_SEQ
   AND a.USERNAME = d.USERNAME
   AND a.TXN_ENTRY_DATE = d.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_DETAIL_SEQ = d.TXN_ENTRY_DETAIL_SEQ
   AND a.ACCOUNT_NBR = e.ACCOUNT_NBR
   AND a.CURRENCY_CODE = e.CURRENCY_CODE
   AND a.BRANCH_CODE = e.BRANCH_CODE
   AND a.COMPANY_CODE = e.COMPANY_CODE
   AND a.CORRESPONDENT_BRANCH_CODE = e.CORRESPONDENT_BRANCH_CODE
   AND a.CONCILIATION_STATE = 'C'
   AND a.DIFFERENCEVALUE IS NOT NULL
   AND e.ACCOUNT_NBR = :p_account_nbr
   AND e.CURRENCY_CODE = NVL(:p_currency_code, a.CURRENCY_CODE)
   AND e.CORRESPONDENT_BRANCH_CODE = :p_correspondent_code
   AND a.DIFFERENCEVALUE > 0
   AND NVL(f.GLOBAL_RECONCILIATION, 'N') = 'S'
 UNION
SELECT d.TXN_ENTRY_SEQ                    AS txn_seq_cr_dif,
       d.USERNAME                         AS user_cr_dif,
       d.TXN_ENTRY_DATE                   AS date_cr_dif,
       d.TXN_ENTRY_DETAIL_SEQ             AS detail_seq_cr_dif,
       d.REFERENCE_NBR                    AS doc_nbr_cr_dif,
       a.DIFFERENCEVALUE                       AS amount_cr_dif,
       b.CONCEPT_TXN_CODE                 AS trn_cr_dif,
       b.AUXILIARY_APPLICATION_CODE       AS app_cr_dif,
       'Transaction generated by reconciliation difference' AS detail_cr_dif
  FROM BC_HISTORICAL_DAILY_RECONCILIATION a,
       BC_TXN_ENTRIES b,
       BC_TXN_ENTRY_DETAILS d,
       BC_ACCOUNTS_RELATED e,
       BC_PARAMETERS_GENERAL f
 WHERE a.TXN_ENTRY_SEQ = b.TXN_ENTRY_SEQ
   AND a.USERNAME = b.USER_CODE
   AND a.TXN_ENTRY_DATE = b.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_SEQ = d.TXN_ENTRY_SEQ
   AND a.USERNAME = d.USERNAME
   AND a.TXN_ENTRY_DATE = d.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_DETAIL_SEQ = d.TXN_ENTRY_DETAIL_SEQ
   AND a.ACCOUNT_NBR = e.ACCOUNT_NBR
   AND a.CURRENCY_CODE = e.CURRENCY_CODE
   AND a.BRANCH_CODE = e.BRANCH_CODE
   AND a.COMPANY_CODE = e.COMPANY_CODE
   AND a.CORRESPONDENT_BRANCH_CODE = e.CORRESPONDENT_BRANCH_CODE
   AND a.CONCILIATION_STATE = 'C'
   AND a.DIFFERENCEVALUE IS NOT NULL
   AND e.ACCOUNT_NBR = :p_account_nbr
   AND e.CURRENCY_CODE = NVL(:p_currency_code, a.CURRENCY_CODE)
   AND e.CORRESPONDENT_BRANCH_CODE = :p_correspondent_code
   AND a.DIFFERENCEVALUE > 0
   AND NVL(f.GLOBAL_RECONCILIATION, 'N') = 'S'
 ORDER BY date_cr_dif ASC


-- Q_db_dif_conciliacion (Debit Reconciliation Differences)
-- Parameters:
--   1. :p_numero_cuenta AS :p_account_nbr - Account number filter
--   2. :p_codigo_moneda AS :p_currency_code - Currency code filter (optional, can be NULL)
--   3. :p_codigo_corresponsal AS :p_correspondent_code - Correspondent branch code filter
--   4. :p_codigo_agencia AS :p_branch_code - Branch code filter
-- Fields:
--   1. secuencia_movimiento -> TXN_ENTRY_SEQ AS txn_seq_db_dif
--   2. codigo_usuario_movimiento -> USERNAME AS user_db_dif
--   3. fecha_movimiento -> TXN_ENTRY_DATE AS date_db_dif
--   4. secuencia_movimiento_detalle -> TXN_ENTRY_DETAIL_SEQ AS detail_seq_db_dif
--   5. numero_documento -> DOCUMENT_NBR AS doc_nbr_db_dif
--   6. numero_referencia -> REFERENCE_NBR AS doc_nbr_db_dif
--   7. diferencia -> DIFFERENCEVALUE AS amount_db_dif
--   8. codigo_transaccion_concepto -> CONCEPT_TXN_CODE AS trn_db_dif
--   9. codigo_aplicacion_auxiliar -> AUXILIARY_APPLICATION_CODE AS app_db_dif
--   10. 'Transaction generated by reconciliation difference' AS detail_db_dif
--   11. codigo_tipo_transaccion -> TXN_TYPE_CODE
--   12. codigo_aplicacion_origen -> ORIGIN_APPLICATION_CODE
--   13. debito_credito_otro -> DEBIT_CREDIT_OTHER
SELECT d.TXN_ENTRY_SEQ                    AS txn_seq_db_dif,
       d.USERNAME                         AS user_db_dif,
       d.TXN_ENTRY_DATE                   AS date_db_dif,
       d.TXN_ENTRY_DETAIL_SEQ             AS detail_seq_db_dif,
       d.DOCUMENT_NBR                     AS doc_nbr_db_dif,
       a.DIFFERENCEVALUE                       AS amount_db_dif,
       b.CONCEPT_TXN_CODE                 AS trn_db_dif,
       b.AUXILIARY_APPLICATION_CODE       AS app_db_dif,
       'Transaction generated by reconciliation difference' AS detail_db_dif
  FROM BC_HISTORICAL_DAILY_RECONCILIATION a,
       BC_TXN_ENTRIES_HISTORICAL b,
       BC_DETAILS_HISTORICAL d,
       BC_PARAMETERS_GENERAL f
 WHERE a.TXN_ENTRY_SEQ = b.TXN_ENTRY_SEQ
   AND a.USERNAME = b.USER_CODE
   AND a.TXN_ENTRY_DATE = b.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_SEQ = d.TXN_ENTRY_SEQ
   AND a.USERNAME = d.USERNAME
   AND a.TXN_ENTRY_DATE = d.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_DETAIL_SEQ = d.TXN_ENTRY_DETAIL_SEQ
   AND a.CONCILIATION_STATE = 'C'
   AND a.DIFFERENCEVALUE IS NOT NULL
   AND a.ACCOUNT_NBR = :p_account_nbr
   AND a.CURRENCY_CODE = NVL(:p_currency_code, a.CURRENCY_CODE)
   AND a.CORRESPONDENT_BRANCH_CODE = :p_correspondent_code
   AND a.BRANCH_CODE = :p_branch_code
   AND a.DIFFERENCEVALUE < 0
   AND NVL(f.GLOBAL_RECONCILIATION, 'N') = 'N'
 UNION
SELECT d.TXN_ENTRY_SEQ                    AS txn_seq_db_dif,
       d.USERNAME                         AS user_db_dif,
       d.TXN_ENTRY_DATE                   AS date_db_dif,
       d.TXN_ENTRY_DETAIL_SEQ             AS detail_seq_db_dif,
       d.REFERENCE_NBR                    AS doc_nbr_db_dif,
       a.DIFFERENCEVALUE                       AS amount_db_dif,
       b.CONCEPT_TXN_CODE                 AS trn_db_dif,
       b.AUXILIARY_APPLICATION_CODE       AS app_db_dif,
       'Transaction generated by reconciliation difference' AS detail_db_dif
  FROM BC_HISTORICAL_DAILY_RECONCILIATION a,
       BC_TXN_ENTRIES b,
       BC_TXN_ENTRY_DETAILS d,
       MG_TRANSACTION_TYPES c,
       BC_PARAMETERS_GENERAL f
 WHERE a.TXN_ENTRY_SEQ = b.TXN_ENTRY_SEQ
   AND a.USERNAME = b.USER_CODE
   AND a.TXN_ENTRY_DATE = b.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_SEQ = d.TXN_ENTRY_SEQ
   AND a.USERNAME = d.USERNAME
   AND a.TXN_ENTRY_DATE = d.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_DETAIL_SEQ = d.TXN_ENTRY_DETAIL_SEQ
   AND b.TXN_TYPE_CODE = c.TXN_TYPE_CODE
   AND b.ORIGIN_APPLICATION_CODE = c.APPLICATION_CODE
   AND c.DEBIT_CREDIT_OTHER = 'D'
   AND a.CONCILIATION_STATE = 'C'
   AND a.DIFFERENCEVALUE IS NOT NULL
   AND a.ACCOUNT_NBR = :p_account_nbr
   AND a.CURRENCY_CODE = NVL(:p_currency_code, a.CURRENCY_CODE)
   AND a.CORRESPONDENT_BRANCH_CODE = :p_correspondent_code
   AND a.BRANCH_CODE = :p_branch_code
   AND a.DIFFERENCEVALUE < 0
   AND NVL(f.GLOBAL_RECONCILIATION, 'N') = 'N'
 UNION
SELECT d.TXN_ENTRY_SEQ                    AS txn_seq_db_dif,
       d.USERNAME                         AS user_db_dif,
       d.TXN_ENTRY_DATE                   AS date_db_dif,
       d.TXN_ENTRY_DETAIL_SEQ             AS detail_seq_db_dif,
       d.DOCUMENT_NBR                     AS doc_nbr_db_dif,
       a.DIFFERENCEVALUE                       AS amount_db_dif,
       b.CONCEPT_TXN_CODE                 AS trn_db_dif,
       b.AUXILIARY_APPLICATION_CODE       AS app_db_dif,
       'Transaction generated by reconciliation difference' AS detail_db_dif
  FROM BC_HISTORICAL_DAILY_RECONCILIATION a,
       BC_TXN_ENTRIES_HISTORICAL b,
       BC_DETAILS_HISTORICAL d,
       BC_ACCOUNTS_RELATED e,
       BC_PARAMETERS_GENERAL f
 WHERE a.TXN_ENTRY_SEQ = b.TXN_ENTRY_SEQ
   AND a.USERNAME = b.USER_CODE
   AND a.TXN_ENTRY_DATE = b.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_SEQ = d.TXN_ENTRY_SEQ
   AND a.USERNAME = d.USERNAME
   AND a.TXN_ENTRY_DATE = d.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_DETAIL_SEQ = d.TXN_ENTRY_DETAIL_SEQ
   AND a.ACCOUNT_NBR = e.ACCOUNT_NBR
   AND a.CURRENCY_CODE = e.CURRENCY_CODE
   AND a.BRANCH_CODE = e.BRANCH_CODE
   AND a.COMPANY_CODE = e.COMPANY_CODE
   AND a.CORRESPONDENT_BRANCH_CODE = e.CORRESPONDENT_BRANCH_CODE
   AND a.CONCILIATION_STATE = 'C'
   AND a.DIFFERENCEVALUE IS NOT NULL
   AND e.ACCOUNT_NBR = :p_account_nbr
   AND e.CURRENCY_CODE = NVL(:p_currency_code, a.CURRENCY_CODE)
   AND e.CORRESPONDENT_BRANCH_CODE = :p_correspondent_code
   AND a.DIFFERENCEVALUE < 0
   AND NVL(f.GLOBAL_RECONCILIATION, 'N') = 'S'
 UNION
SELECT d.TXN_ENTRY_SEQ                    AS txn_seq_db_dif,
       d.USERNAME                         AS user_db_dif,
       d.TXN_ENTRY_DATE                   AS date_db_dif,
       d.TXN_ENTRY_DETAIL_SEQ             AS detail_seq_db_dif,
       d.REFERENCE_NBR                    AS doc_nbr_db_dif,
       a.DIFFERENCEVALUE                       AS amount_db_dif,
       b.CONCEPT_TXN_CODE                 AS trn_db_dif,
       b.AUXILIARY_APPLICATION_CODE       AS app_db_dif,
       'Transaction generated by reconciliation difference' AS detail_db_dif
  FROM BC_HISTORICAL_DAILY_RECONCILIATION a,
       BC_TXN_ENTRIES b,
       BC_TXN_ENTRY_DETAILS d,
       MG_TRANSACTION_TYPES c,
       BC_ACCOUNTS_RELATED e,
       BC_PARAMETERS_GENERAL f
 WHERE a.TXN_ENTRY_SEQ = b.TXN_ENTRY_SEQ
   AND a.USERNAME = b.USER_CODE
   AND a.TXN_ENTRY_DATE = b.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_SEQ = d.TXN_ENTRY_SEQ
   AND a.USERNAME = d.USERNAME
   AND a.TXN_ENTRY_DATE = d.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_DETAIL_SEQ = d.TXN_ENTRY_DETAIL_SEQ
   AND a.ACCOUNT_NBR = e.ACCOUNT_NBR
   AND a.CURRENCY_CODE = e.CURRENCY_CODE
   AND a.BRANCH_CODE = e.BRANCH_CODE
   AND a.COMPANY_CODE = e.COMPANY_CODE
   AND a.CORRESPONDENT_BRANCH_CODE = e.CORRESPONDENT_BRANCH_CODE
   AND b.TXN_TYPE_CODE = c.TXN_TYPE_CODE
   AND b.ORIGIN_APPLICATION_CODE = c.APPLICATION_CODE
   AND c.DEBIT_CREDIT_OTHER = 'D'
   AND a.CONCILIATION_STATE = 'C'
   AND a.DIFFERENCEVALUE IS NOT NULL
   AND e.ACCOUNT_NBR = :p_account_nbr
   AND e.CURRENCY_CODE = NVL(:p_currency_code, a.CURRENCY_CODE)
   AND e.CORRESPONDENT_BRANCH_CODE = :p_correspondent_code
   AND a.DIFFERENCEVALUE < 0
   AND NVL(f.GLOBAL_RECONCILIATION, 'N') = 'S'
 ORDER BY date_db_dif ASC


-- Q_extractos_creditos (Statement Credits)
-- Parameters:
--   1. :p_numero_cuenta AS :p_account_nbr - Account number filter
--   2. :p_codigo_moneda AS :p_currency_code - Currency code filter (optional, can be NULL)
--   3. :p_codigo_corresponsal AS :p_correspondent_code - Correspondent branch code filter
--   4. :p_fecha AS :p_date - Date filter for year/month comparison and ordering
-- Fields:
--   1. numero_cuenta -> ACCOUNT_NBR
--   2. codigo_moneda -> CURRENCY_CODE
--   3. codigo_agencia -> BRANCH_CODE
--   4. codigo_agencia_corresponsal -> CORRESPONDENT_BRANCH_CODE
--   5. codigo_empresa -> COMPANY_CODE
--   6. secuencia_detalle -> DETAIL_SEQ
--   7. dia -> DAY
--   8. ano -> YEAR
--   9. mes -> MONTH
--   10. monto -> AMOUNT
--   11. numero_documento -> DOCUMENT_NBR
--   12. descripcion -> DESCRIPTION
--   13. TO_DATE(TO_CHAR(a.DAY)||'-'||TO_CHAR(a.MONTH)||'-'||TO_CHAR(a.YEAR),'DD-MM-YYYY') AS statement_date_cr
--   14. codigo_transaccion -> TXN_CODE
--   15. estado_conciliacion -> RECONCILIATION_STATUS
--   16. efecto -> EFFECT
SELECT b.ACCOUNT_NBR,
       b.CURRENCY_CODE,
       b.BRANCH_CODE,
       b.CORRESPONDENT_BRANCH_CODE,
       b.COMPANY_CODE,
       b.DETAIL_SEQ,
       b.DAY,
       b.YEAR,
       b.MONTH,
       b.AMOUNT,
       b.DOCUMENT_NBR,
       c.DESCRIPTION,
       TO_DATE(TO_CHAR(a.DAY) || '-' || TO_CHAR(a.MONTH) || '-' || TO_CHAR(a.YEAR), 'DD-MM-YYYY') AS statement_date_cr,
       c.TXN_CODE
  FROM BC_EXT_DAILY_RECONCILIATION a,
       BC_DETAIL_STATEMENTS b,
       BC_CORRESPONDENT_TRANSACTIONS c
 WHERE a.ACCOUNT_NBR = b.ACCOUNT_NBR
   AND a.CURRENCY_CODE = b.CURRENCY_CODE
   AND a.BRANCH_CODE = b.BRANCH_CODE
   AND a.CORRESPONDENT_BRANCH_CODE = b.CORRESPONDENT_BRANCH_CODE
   AND a.DETAIL_SEQ = b.DETAIL_SEQ
   AND a.YEAR = b.YEAR
   AND a.MONTH = b.MONTH
   AND b.TXN_CODE = c.TXN_CODE
   AND b.BRANCH_CODE = c.BRANCH_CODE
   AND b.CORRESPONDENT_BRANCH_CODE = c.CORRESPONDENT_BRANCH_CODE
   AND c.EFFECT = 'C'
   AND a.ACCOUNT_NBR = :p_account_nbr
   AND a.CURRENCY_CODE = NVL(:p_currency_code, a.CURRENCY_CODE)
   AND a.CORRESPONDENT_BRANCH_CODE = :p_correspondent_code
   AND a.YEAR <= NVL(TO_NUMBER(TO_CHAR(:p_date, 'YYYY')), a.YEAR)
   AND a.MONTH <= TO_NUMBER(TO_CHAR(:p_date, 'MM'))
   AND a.RECONCILIATION_STATUS <> 'C'
 -- ORDER BY b.DOCUMENT_NBR
 ORDER BY :p_date ASC


-- Q_extractos_debitos (Statement Debits)
-- Parameters:
--   1. :p_numero_cuenta AS :p_account_nbr - Account number filter
--   2. :p_codigo_moneda AS :p_currency_code - Currency code filter (optional, can be NULL)
--   3. :p_codigo_corresponsal AS :p_correspondent_code - Correspondent branch code filter
--   4. :p_fecha AS :p_date - Date filter for year/month comparison and ordering
-- Fields:
--   1. numero_cuenta -> ACCOUNT_NBR
--   2. codigo_moneda -> CURRENCY_CODE
--   3. codigo_agencia -> BRANCH_CODE
--   4. codigo_agencia_corresponsal -> CORRESPONDENT_BRANCH_CODE
--   5. codigo_empresa -> COMPANY_CODE
--   6. secuencia_detalle -> DETAIL_SEQ
--   7. dia -> DAY
--   8. ano -> YEAR
--   9. mes -> MONTH
--   10. estado_conciliacion -> RECONCILIATION_STATUS
--   11. (monto * -1) -> AMOUNT AS amount
--   12. numero_documento -> DOCUMENT_NBR
--   13. descripcion -> DESCRIPTION
--   14. TO_DATE(TO_CHAR(a.DAY)||'-'||TO_CHAR(a.MONTH)||'-'||TO_CHAR(a.YEAR),'DD-MM-YYYY') AS statement_date_db
--   15. codigo_transaccion -> TXN_CODE
--   16. efecto -> EFFECT
SELECT b.ACCOUNT_NBR,
       b.CURRENCY_CODE,
       b.BRANCH_CODE,
       b.CORRESPONDENT_BRANCH_CODE,
       b.COMPANY_CODE,
       b.DETAIL_SEQ,
       b.DAY,
       b.YEAR,
       b.MONTH,
       b.RECONCILIATION_STATUS,
       (b.AMOUNT * -1) AS amount,
       b.DOCUMENT_NBR,
       c.DESCRIPTION,
       TO_DATE(TO_CHAR(a.DAY) || '-' || TO_CHAR(a.MONTH) || '-' || TO_CHAR(a.YEAR), 'DD-MM-YYYY') AS statement_date_db,
       c.TXN_CODE
  FROM BC_EXT_DAILY_RECONCILIATION a,
       BC_DETAIL_STATEMENTS b,
       BC_CORRESPONDENT_TRANSACTIONS c
 WHERE a.ACCOUNT_NBR = b.ACCOUNT_NBR
   AND a.CURRENCY_CODE = b.CURRENCY_CODE
   AND a.BRANCH_CODE = b.BRANCH_CODE
   AND a.CORRESPONDENT_BRANCH_CODE = b.CORRESPONDENT_BRANCH_CODE
   AND a.DETAIL_SEQ = b.DETAIL_SEQ
   AND a.YEAR = b.YEAR
   AND a.MONTH = b.MONTH
   AND b.TXN_CODE = c.TXN_CODE
   AND b.BRANCH_CODE = c.BRANCH_CODE
   AND b.CORRESPONDENT_BRANCH_CODE = c.CORRESPONDENT_BRANCH_CODE
   AND c.EFFECT = 'D'
   AND a.ACCOUNT_NBR = :p_account_nbr
   AND a.CURRENCY_CODE = NVL(:p_currency_code, a.CURRENCY_CODE)
   AND a.CORRESPONDENT_BRANCH_CODE = :p_correspondent_code
   AND a.YEAR <= NVL(TO_NUMBER(TO_CHAR(:p_date, 'YYYY')), a.YEAR)
   AND a.MONTH <= TO_NUMBER(TO_CHAR(:p_date, 'MM'))
   AND a.RECONCILIATION_STATUS <> 'C'
 -- ORDER BY b.DOCUMENT_NBR
 ORDER BY :p_date ASC


-- Q_historicos_creditos (Historical Credits)
-- Parameters:
--   1. :p_numero_cuenta AS :p_account_nbr - Account number filter
--   2. :p_codigo_agencia AS :p_branch_code - Branch code filter
--   3. :p_codigo_moneda AS :p_currency_code - Currency code filter (optional, can be NULL)
--   4. :p_codigo_corresponsal AS :p_correspondent_code - Correspondent branch code filter
-- Fields:
--   1. secuencia_movimiento -> TXN_ENTRY_SEQ
--   2. codigo_usuario_movimiento -> USERNAME
--   3. fecha_movimiento -> TXN_ENTRY_DATE
--   4. secuencia_movimiento_detalle -> TXN_ENTRY_DETAIL_SEQ
--   5. numero_documento -> DOCUMENT_NBR 
--   6. valor_movimiento -> TXN_ENTRY_AMOUNT AS amount
--   7. codigo_transaccion_concepto -> CONCEPT_TXN_CODE AS trn_cr
--   8. codigo_aplicacion_auxiliar -> AUXILIARY_APPLICATION_CODE AS app_cr
--   9. debito_credito_otro -> DEBIT_CREDIT_OTHER
--   10. descripcion (tipo transaccion) -> DESCRIPTION
--   11. descripcion (detalle) -> DESCRIPTION AS detail_hist_cr
--   12. estado_conciliacion -> CONCILIATION_STATE
--   13. conciliacion_global -> GLOBAL_RECONCILIATION
SELECT d.TXN_ENTRY_SEQ,
       d.USERNAME,
       d.TXN_ENTRY_DATE,
       d.TXN_ENTRY_DETAIL_SEQ,
       d.DOCUMENT_NBR,
       d.TXN_ENTRY_AMOUNT             AS amount,
       b.CONCEPT_TXN_CODE             AS trn_cr,
       b.AUXILIARY_APPLICATION_CODE   AS app_cr,
       c.DEBIT_CREDIT_OTHER,
       c.DESCRIPTION,
       d.DESCRIPTION                  AS detail_hist_cr
  FROM BC_HISTORICAL_DAILY_RECONCILIATION a,
       BC_TXN_ENTRIES_HISTORICAL b,
       BC_DETAILS_HISTORICAL d,
       MG_TRANSACTION_TYPES c,
       BC_PARAMETERS_GENERAL f
 WHERE a.TXN_ENTRY_SEQ = b.TXN_ENTRY_SEQ
   AND a.USERNAME = b.USER_CODE
   AND a.TXN_ENTRY_DATE = b.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_SEQ = d.TXN_ENTRY_SEQ
   AND a.USERNAME = d.USERNAME
   AND a.TXN_ENTRY_DATE = d.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_DETAIL_SEQ = d.TXN_ENTRY_DETAIL_SEQ
   AND b.TXN_TYPE_CODE = c.TXN_TYPE_CODE
   AND b.APPLICATION_CODE = c.APPLICATION_CODE
   AND c.DEBIT_CREDIT_OTHER = 'C'
   AND a.ACCOUNT_NBR = :p_account_nbr
   AND a.BRANCH_CODE = :p_branch_code
   AND a.CURRENCY_CODE = NVL(:p_currency_code, a.CURRENCY_CODE)
   AND a.CORRESPONDENT_BRANCH_CODE = :p_correspondent_code
   AND a.CONCILIATION_STATE <> 'C'
   AND NVL(f.GLOBAL_RECONCILIATION, 'N') = 'N'
 UNION
SELECT d.TXN_ENTRY_SEQ,
       d.USERNAME,
       d.TXN_ENTRY_DATE,
       d.TXN_ENTRY_DETAIL_SEQ,
       d.REFERENCE_NBR                AS reference_nbr,
       d.TXN_ENTRY_AMOUNT             AS amount,
       b.CONCEPT_TXN_CODE             AS trn_cr,
       b.AUXILIARY_APPLICATION_CODE   AS app_cr,
       c.DEBIT_CREDIT_OTHER,
       c.DESCRIPTION,
       d.DESCRIPTION                  AS detail_hist_cr
  FROM BC_HISTORICAL_DAILY_RECONCILIATION a,
       BC_TXN_ENTRIES b,
       BC_TXN_ENTRY_DETAILS d,
       MG_TRANSACTION_TYPES c,
       BC_PARAMETERS_GENERAL f
 WHERE a.TXN_ENTRY_SEQ = b.TXN_ENTRY_SEQ
   AND a.USERNAME = b.USER_CODE
   AND a.TXN_ENTRY_DATE = b.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_SEQ = d.TXN_ENTRY_SEQ
   AND a.USERNAME = d.USERNAME
   AND a.TXN_ENTRY_DATE = d.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_DETAIL_SEQ = d.TXN_ENTRY_DETAIL_SEQ
   AND b.TXN_TYPE_CODE = c.TXN_TYPE_CODE
   AND b.APPLICATION_CODE = c.APPLICATION_CODE
   AND c.DEBIT_CREDIT_OTHER = 'C'
   AND a.ACCOUNT_NBR = :p_account_nbr
   AND a.CURRENCY_CODE = NVL(:p_currency_code, a.CURRENCY_CODE)
   AND a.CORRESPONDENT_BRANCH_CODE = :p_correspondent_code
   AND a.BRANCH_CODE = :p_branch_code
   AND a.CONCILIATION_STATE <> 'C'
   AND NVL(f.GLOBAL_RECONCILIATION, 'N') = 'N'
 UNION
SELECT d.TXN_ENTRY_SEQ,
       d.USERNAME,
       d.TXN_ENTRY_DATE,
       d.TXN_ENTRY_DETAIL_SEQ,
       d.DOCUMENT_NBR,
       d.TXN_ENTRY_AMOUNT             AS amount,
       b.CONCEPT_TXN_CODE             AS trn_cr,
       b.AUXILIARY_APPLICATION_CODE   AS app_cr,
       c.DEBIT_CREDIT_OTHER,
       c.DESCRIPTION,
       d.DESCRIPTION                  AS detail_hist_cr
  FROM BC_HISTORICAL_DAILY_RECONCILIATION a,
       BC_TXN_ENTRIES_HISTORICAL b,
       BC_DETAILS_HISTORICAL d,
       MG_TRANSACTION_TYPES c,
       BC_ACCOUNTS_RELATED e,
       BC_PARAMETERS_GENERAL f
 WHERE a.TXN_ENTRY_SEQ = b.TXN_ENTRY_SEQ
   AND a.USERNAME = b.USER_CODE
   AND a.TXN_ENTRY_DATE = b.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_SEQ = d.TXN_ENTRY_SEQ
   AND a.USERNAME = d.USERNAME
   AND a.TXN_ENTRY_DATE = d.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_DETAIL_SEQ = d.TXN_ENTRY_DETAIL_SEQ
   AND a.ACCOUNT_NBR = e.ACCOUNT_NBR
   AND a.CURRENCY_CODE = e.CURRENCY_CODE
   AND a.BRANCH_CODE = e.BRANCH_CODE
   AND a.COMPANY_CODE = e.COMPANY_CODE
   AND a.CORRESPONDENT_BRANCH_CODE = e.CORRESPONDENT_BRANCH_CODE
   AND b.TXN_TYPE_CODE = c.TXN_TYPE_CODE
   AND b.APPLICATION_CODE = c.APPLICATION_CODE
   AND c.DEBIT_CREDIT_OTHER = 'C'
   AND e.ACCOUNT_NBR = :p_account_nbr
   AND e.CURRENCY_CODE = NVL(:p_currency_code, a.CURRENCY_CODE)
   AND e.CORRESPONDENT_BRANCH_CODE = :p_correspondent_code
   AND a.CONCILIATION_STATE <> 'C'
   AND NVL(f.GLOBAL_RECONCILIATION, 'N') = 'S'
 UNION
SELECT d.TXN_ENTRY_SEQ,
       d.USERNAME,
       d.TXN_ENTRY_DATE,
       d.TXN_ENTRY_DETAIL_SEQ,
       d.REFERENCE_NBR                AS reference_nbr,
       d.TXN_ENTRY_AMOUNT             AS amount,
       b.CONCEPT_TXN_CODE             AS trn_cr,
       b.AUXILIARY_APPLICATION_CODE   AS app_cr,
       c.DEBIT_CREDIT_OTHER,
       c.DESCRIPTION,
       d.DESCRIPTION                  AS detail_hist_cr
  FROM BC_HISTORICAL_DAILY_RECONCILIATION a,
       BC_TXN_ENTRIES b,
       BC_TXN_ENTRY_DETAILS d,
       MG_TRANSACTION_TYPES c,
       BC_ACCOUNTS_RELATED e,
       BC_PARAMETERS_GENERAL f
 WHERE a.TXN_ENTRY_SEQ = b.TXN_ENTRY_SEQ
   AND a.USERNAME = b.USER_CODE
   AND a.TXN_ENTRY_DATE = b.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_SEQ = d.TXN_ENTRY_SEQ
   AND a.USERNAME = d.USERNAME
   AND a.TXN_ENTRY_DATE = d.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_DETAIL_SEQ = d.TXN_ENTRY_DETAIL_SEQ
   AND a.ACCOUNT_NBR = e.ACCOUNT_NBR
   AND a.CURRENCY_CODE = e.CURRENCY_CODE
   AND a.BRANCH_CODE = e.BRANCH_CODE
   AND a.COMPANY_CODE = e.COMPANY_CODE
   AND a.CORRESPONDENT_BRANCH_CODE = e.CORRESPONDENT_BRANCH_CODE
   AND b.TXN_TYPE_CODE = c.TXN_TYPE_CODE
   AND b.APPLICATION_CODE = c.APPLICATION_CODE
   AND c.DEBIT_CREDIT_OTHER = 'C'
   AND e.ACCOUNT_NBR = :p_account_nbr
   AND e.CURRENCY_CODE = NVL(:p_currency_code, a.CURRENCY_CODE)
   AND e.CORRESPONDENT_BRANCH_CODE = :p_correspondent_code
   AND a.CONCILIATION_STATE <> 'C'
   AND NVL(f.GLOBAL_RECONCILIATION, 'N') = 'S'
 -- ORDER BY 5
 ORDER BY TXN_ENTRY_DATE ASC


-- Q_historicos_debitos (Historical Debits)
-- Parameters:
--   1. :p_numero_cuenta AS :p_account_nbr - Account number filter
--   2. :p_codigo_agencia AS :p_branch_code - Branch code filter
--   3. :p_codigo_moneda AS :p_currency_code - Currency code filter (optional, can be NULL)
--   4. :p_codigo_corresponsal AS :p_correspondent_code - Correspondent branch code filter
-- Fields:
--   1. secuencia_movimiento -> TXN_ENTRY_SEQ
--   2. codigo_usuario_movimiento -> USERNAME
--   3. fecha_movimiento -> TXN_ENTRY_DATE
--   4. secuencia_movimiento_detalle -> TXN_ENTRY_DETAIL_SEQ
--   5. numero_documento -> DOCUMENT_NBR (or numero_referencia -> REFERENCE_NBR AS document_nbr)
--   6. (valor_movimiento * -1) -> TXN_ENTRY_AMOUNT AS amount
--   7. codigo_transaccion_concepto -> CONCEPT_TXN_CODE AS trn_db
--   8. codigo_aplicacion_auxiliar -> AUXILIARY_APPLICATION_CODE AS app_db
--   9. debito_credito_otro -> DEBIT_CREDIT_OTHER
--   10. descripcion (tipo transaccion) -> DESCRIPTION
--   11. descripcion (detalle) -> DESCRIPTION AS detail_hist_db
--   12. estado_conciliacion -> CONCILIATION_STATE
--   13. conciliacion_global -> GLOBAL_RECONCILIATION
SELECT d.TXN_ENTRY_SEQ,
       d.USERNAME,
       d.TXN_ENTRY_DATE,
       d.TXN_ENTRY_DETAIL_SEQ,
       d.DOCUMENT_NBR,
       (d.TXN_ENTRY_AMOUNT * -1)      AS amount,
       b.CONCEPT_TXN_CODE             AS trn_db,
       b.AUXILIARY_APPLICATION_CODE   AS app_db,
       c.DEBIT_CREDIT_OTHER,
       c.DESCRIPTION,
       d.DESCRIPTION                  AS detail_hist_db
  FROM BC_HISTORICAL_DAILY_RECONCILIATION a,
       BC_TXN_ENTRIES_HISTORICAL b,
       BC_DETAILS_HISTORICAL d,
       MG_TRANSACTION_TYPES c,
       BC_PARAMETERS_GENERAL f
 WHERE a.TXN_ENTRY_SEQ = b.TXN_ENTRY_SEQ
   AND a.USERNAME = b.USER_CODE
   AND a.TXN_ENTRY_DATE = b.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_SEQ = d.TXN_ENTRY_SEQ
   AND a.USERNAME = d.USERNAME
   AND a.TXN_ENTRY_DATE = d.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_DETAIL_SEQ = d.TXN_ENTRY_DETAIL_SEQ
   AND b.TXN_TYPE_CODE = c.TXN_TYPE_CODE
   AND b.APPLICATION_CODE = c.APPLICATION_CODE
   AND c.DEBIT_CREDIT_OTHER = 'D'
   AND a.ACCOUNT_NBR = :p_account_nbr
   AND a.BRANCH_CODE = :p_branch_code
   AND a.CURRENCY_CODE = NVL(:p_currency_code, a.CURRENCY_CODE)
   AND a.CORRESPONDENT_BRANCH_CODE = :p_correspondent_code
   AND a.CONCILIATION_STATE <> 'C'
   AND NVL(f.GLOBAL_RECONCILIATION, 'N') = 'N'
 UNION
SELECT d.TXN_ENTRY_SEQ,
       d.USERNAME,
       d.TXN_ENTRY_DATE,
       d.TXN_ENTRY_DETAIL_SEQ,
       d.REFERENCE_NBR                AS document_nbr,
       (d.TXN_ENTRY_AMOUNT * -1)      AS amount,
       /* amount, difference */
       b.CONCEPT_TXN_CODE             AS trn_db,
       b.AUXILIARY_APPLICATION_CODE   AS app_db,
       c.DEBIT_CREDIT_OTHER,
       c.DESCRIPTION,
       d.DESCRIPTION                  AS detail_hist_db
  FROM BC_HISTORICAL_DAILY_RECONCILIATION a,
       BC_TXN_ENTRIES b,
       BC_TXN_ENTRY_DETAILS d,
       MG_TRANSACTION_TYPES c,
       BC_PARAMETERS_GENERAL f
 WHERE a.TXN_ENTRY_SEQ = b.TXN_ENTRY_SEQ
   AND a.USERNAME = b.USER_CODE
   AND a.TXN_ENTRY_DATE = b.TXN_ENTRY_DATE
   AND b.TXN_TYPE_CODE = c.TXN_TYPE_CODE
   AND b.APPLICATION_CODE = c.APPLICATION_CODE
   AND a.TXN_ENTRY_SEQ = d.TXN_ENTRY_SEQ
   AND a.USERNAME = d.USERNAME
   AND a.TXN_ENTRY_DATE = d.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_DETAIL_SEQ = d.TXN_ENTRY_DETAIL_SEQ
   AND c.DEBIT_CREDIT_OTHER = 'D'
   AND a.ACCOUNT_NBR = :p_account_nbr
   AND a.BRANCH_CODE = :p_branch_code
   AND a.CURRENCY_CODE = NVL(:p_currency_code, a.CURRENCY_CODE)
   AND a.CORRESPONDENT_BRANCH_CODE = :p_correspondent_code
   AND a.CONCILIATION_STATE <> 'C'
   AND NVL(f.GLOBAL_RECONCILIATION, 'N') = 'N'
 UNION
SELECT d.TXN_ENTRY_SEQ,
       d.USERNAME,
       d.TXN_ENTRY_DATE,
       d.TXN_ENTRY_DETAIL_SEQ,
       d.DOCUMENT_NBR,
       (d.TXN_ENTRY_AMOUNT * -1)      AS amount,
       b.CONCEPT_TXN_CODE             AS trn_db,
       b.AUXILIARY_APPLICATION_CODE   AS app_db,
       c.DEBIT_CREDIT_OTHER,
       c.DESCRIPTION,
       d.DESCRIPTION                  AS detail_hist_db
  FROM BC_HISTORICAL_DAILY_RECONCILIATION a,
       BC_TXN_ENTRIES_HISTORICAL b,
       BC_DETAILS_HISTORICAL d,
       MG_TRANSACTION_TYPES c,
       BC_ACCOUNTS_RELATED e,
       BC_PARAMETERS_GENERAL f
 WHERE a.TXN_ENTRY_SEQ = b.TXN_ENTRY_SEQ
   AND a.USERNAME = b.USER_CODE
   AND a.TXN_ENTRY_DATE = b.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_SEQ = d.TXN_ENTRY_SEQ
   AND a.USERNAME = d.USERNAME
   AND a.TXN_ENTRY_DATE = d.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_DETAIL_SEQ = d.TXN_ENTRY_DETAIL_SEQ
   AND a.ACCOUNT_NBR = e.ACCOUNT_NBR
   AND a.CURRENCY_CODE = e.CURRENCY_CODE
   AND a.BRANCH_CODE = e.BRANCH_CODE
   AND a.COMPANY_CODE = e.COMPANY_CODE
   AND a.CORRESPONDENT_BRANCH_CODE = e.CORRESPONDENT_BRANCH_CODE
   AND b.TXN_TYPE_CODE = c.TXN_TYPE_CODE
   AND b.APPLICATION_CODE = c.APPLICATION_CODE
   AND c.DEBIT_CREDIT_OTHER = 'D'
   AND e.ACCOUNT_NBR = :p_account_nbr
   AND e.CURRENCY_CODE = NVL(:p_currency_code, a.CURRENCY_CODE)
   AND e.CORRESPONDENT_BRANCH_CODE = :p_correspondent_code
   AND a.CONCILIATION_STATE <> 'C'
   AND NVL(f.GLOBAL_RECONCILIATION, 'N') = 'S'
 UNION
SELECT d.TXN_ENTRY_SEQ,
       d.USERNAME,
       d.TXN_ENTRY_DATE,
       d.TXN_ENTRY_DETAIL_SEQ,
       d.REFERENCE_NBR                AS document_nbr,
       (d.TXN_ENTRY_AMOUNT * -1)      AS amount,
       /* amount, difference */
       b.CONCEPT_TXN_CODE             AS trn_db,
       b.AUXILIARY_APPLICATION_CODE   AS app_db,
       c.DEBIT_CREDIT_OTHER,
       c.DESCRIPTION,
       d.DESCRIPTION                  AS detail_hist_db
  FROM BC_HISTORICAL_DAILY_RECONCILIATION a,
       BC_TXN_ENTRIES b,
       BC_TXN_ENTRY_DETAILS d,
       MG_TRANSACTION_TYPES c,
       BC_ACCOUNTS_RELATED e,
       BC_PARAMETERS_GENERAL f
 WHERE a.TXN_ENTRY_SEQ = b.TXN_ENTRY_SEQ
   AND a.USERNAME = b.USER_CODE
   AND a.TXN_ENTRY_DATE = b.TXN_ENTRY_DATE
   AND b.TXN_TYPE_CODE = c.TXN_TYPE_CODE
   AND b.APPLICATION_CODE = c.APPLICATION_CODE
   AND a.TXN_ENTRY_SEQ = d.TXN_ENTRY_SEQ
   AND a.USERNAME = d.USERNAME
   AND a.TXN_ENTRY_DATE = d.TXN_ENTRY_DATE
   AND a.TXN_ENTRY_DETAIL_SEQ = d.TXN_ENTRY_DETAIL_SEQ
   AND a.ACCOUNT_NBR = e.ACCOUNT_NBR
   AND a.CURRENCY_CODE = e.CURRENCY_CODE
   AND a.BRANCH_CODE = e.BRANCH_CODE
   AND a.COMPANY_CODE = e.COMPANY_CODE
   AND a.CORRESPONDENT_BRANCH_CODE = e.CORRESPONDENT_BRANCH_CODE
   AND c.DEBIT_CREDIT_OTHER = 'D'
   AND e.ACCOUNT_NBR = :p_account_nbr
   AND e.CURRENCY_CODE = NVL(:p_currency_code, a.CURRENCY_CODE)
   AND e.CORRESPONDENT_BRANCH_CODE = :p_correspondent_code
   AND a.CONCILIATION_STATE <> 'C'
   AND NVL(f.GLOBAL_RECONCILIATION, 'N') = 'S'
 ORDER BY TXN_ENTRY_DATE ASC